[package]
name = "pow_client"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }

[dependencies]
dotenv = { workspace = true }

pow_core = { workspace = true }
