[package]
name = "pow_common"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }

[dependencies]
dotenv = { workspace = true }
env_logger = { workspace = true }
sha256 = { workspace = true }
hex = { workspace = true }
