pub const DEFAULT_NODE_PORT: u16 = 8080;
pub const DEFAULT_MAX_CONNECTIONS: usize = 1000;
pub const DEFAULT_MAX_BODY_SIZE: usize = 1024;
pub const DEFAULT_BLOCK_DURATION_SEC: u64 = 10;
pub const DEFAULT_UPDATE_DIFFICULTY_INTERVAL: u64 = 100;
pub const DEFAULT_DIFFICULTY_UPDATE_CAP: f64 = 4.0;
